### ISSUE TITLE
LUDE is not operational at this moment (10am California time, 8/13

### ISSUE THREAD

**Issue by mkgilson** [Capigol/LUDe_v2#1]

**Comment by Capigol** [comment]
Dear Michael Gilson,
Thank you for reaching out regarding the issues in the GitHub repository. We have successfully and temporarily resolved the errors, and the code is now functioning correctly. However, this code has some limitations since it has been designed to run on the streamlit platform. We also developed an enhanced version of the code that utilizes Open Babel for a better charge optimization. You can find this enhanced version at the following link: https://github.com/LIDeB/LUDe.v1.0

Let us know if you have any questions or feedback. 

Best regards,
